config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resources :pins
  
  root "pins#index"

  resources :pins

  put "/pins/:id/like", to: "pins#like", as: "like"

  delete "/likes/:id", to: "likes#unlike", as: "unlike"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: {scope: :pin_id}
  belongs_to :user
  belongs_to :pin
end

app/models/pin.rb
class Pin < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:usuário, :moderador, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end

  has_many :pins, dependent: :destroy 
  has_many :likes, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def unlike
        @pins = Pin.all.find(params[:id])
        @like = Like.find_by(pin_id: params[:id], user_id: current_user.id)
		@like.destroy
		redirect_to pin_path(@pins)
	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

	before_action :authenticate_user!, except:[:index, :show]
	before_action :correct_user?, only:[:edit, :update, :destroy]

	def index
		@pins = Pin.all
	end
	
	def show
		@pins = Pin.find(params[:id])
	end
	
	def new
		@pins = current_user.pins.build
	end
	
	def create
		@pins = current_user.pins.build(pin_params)
		
		if @pins.save
			redirect_to @pins, notice: "Pin criado com sucesso"
		else
			render :new
		end
	end
	
	def edit
		@pins = Pin.find(params[:id])
	end
	
	def update
		@pins = Pin.find(params[:id])
		
		if @pins.update(pin_params)
			redirect_to @pins, notice: "Pin alterado com sucesso"		
		else
			reder :edit, status: :unprocessable_entity
		end
	end
	
	def destroy
		@pins = Pin.find(params[:id])
		@pins.destroy

		redirect_to root_path, status: :see_other, notice: "Pin removido com sucesso"
	end

	def like
		@pins = Pin.all.find(params[:id])
		Like.create(pin_id: @pins.id, user_id: current_user.id)
		redirect_to pin_path(@pins)
	end
	
	private
	
	def pin_params
		params.require(:pin).permit(:title, :description)
	end

	def correct_user?
        @pins = current_user.pins.find_by(id: params[:id])
        redirect_to pin_path, notice: "Not authorized to edit this pin" if @pins.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterested2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
      <%= render 'pins/header' %>
      <% if !notice.nil? %>
        <div class="alert alert-primary" role="alert"><%= notice %><%= alert %></div>
      <% end %>
      <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with model: @pins do |form| %>
	<div>
		<%= form.label :title, 'Pin'%><br>
		<%= form.text_field :title %>
	</div>
	
	<div>
		<%= form.label :descrpition, 'Descrição' %><br>
		<%= form.text_area :description %><br>
	</div>
	
	<div>
		<%= form.submit "Criar Pin" %>
	</div>
<% end %>

app/views/pins/_header.html.erb
<%= link_to "Inicio", root_path %> | 
<% if current_user %>
	<%= link_to "Sair", destroy_user_session_path, 'data-turbo-method': :delete %> | 
    <%= link_to "Configurações", edit_user_registration_path %>
<%else%>
	<%= link_to "Entre", new_user_session_path %> | 
	<%= link_to "Cadastre-se", new_user_registration_path %>
<%end%>

app/views/pins/edit.html.erb
<h1>Editar Pin</h1>
<%= render 'form', pin: @pins %>

app/views/pins/index.html.erb
<% if current_user %>
	<p>Olá, <%= current_user.email%>! você está conectado como <%= current_user.role %>!</p>
	<% if current_user.admin? %>
		<p>Há <%= User.count %> usuários salvando e compartilhando Pins!</p>
	<% end %>
<% end %>

<h1>Lista de Pins</h1>

<% @pins.each do |pin| %>
	<%= link_to pin.title, pin %></br>
<% end %><br>

</br><%= link_to "Novo Pin", new_pin_path %>

app/views/pins/new.html.erb
<h1>Novo Pin</h1>
<%= render 'form' %>
<%= link_to "Voltar", root_path %>

app/views/pins/show.html.erb
<h1><%= @pins.title %></h1>

<p><%= @pins.description %></p>

<p>Enviado por <%= @pins.user.email%>, no dia <%= @pins.user.created_at.time.day %>/<%= @pins.user.created_at.time.month %>/<%= @pins.user.created_at.time.year %></p>
<% if current_user %>
    <% if Like.where(:pin => @pins.id, :user => current_user.id).ids[0].nil? %>
        <!-- Não entendi commo funciona o form abaixo -->
        <%= button_to "Like", like_path(@pins), method: "put" %>
    <% else %>
        <%= button_to "Unlike", unlike_path(@pins), method: :delete %> <!-- Como adicionar o Unlike? ou Remover o Like? -->
    <% end %>
    </br></br>
    <%= link_to "Editar Pin", edit_pin_path(@pins) %> | 
    <%= link_to "Apagar Pin", @pins, data:{'method': :delete, 'confirm': "Está certo disso?"} %> |
<% end %>



<%= link_to "Voltar", root_path %>